/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BannerPhoto {
  'uploaderName' : string,
  'photoKey' : string,
  'uploadTimestamp' : Time,
  'uploader' : Principal,
}
export interface CategoryLeaderboard {
  'categoryName' : string,
  'players' : Array<MemberProfileWithRank>,
}
export type EloRating = bigint;
export type ExternalBlob = Uint8Array;
export interface MatchScore {
  'status' : MatchStatus,
  'scoreA' : bigint,
  'scoreB' : bigint,
  'rejectionReason' : [] | [string],
  'kFactor' : bigint,
  'ratingChangeA' : bigint,
  'ratingChangeB' : bigint,
  'playerA' : Principal,
  'playerB' : Principal,
  'timestamp' : Time,
}
export type MatchStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface MemberProfile {
  'id' : Principal,
  'name' : string,
  'rating' : EloRating,
  'photo' : [] | [Photo],
  'matchHistory' : Array<MatchScore>,
}
export interface MemberProfileWithRank {
  'id' : Principal,
  'name' : string,
  'rank' : bigint,
  'rating' : EloRating,
  'photo' : [] | [Photo],
  'matchHistory' : Array<MatchScore>,
}
export interface OneTimeClaimMember {
  'name' : string,
  'eloRating' : bigint,
  'createdTimestamp' : Time,
  'photo' : [] | [Photo],
}
export type Photo = Uint8Array;
export interface PhotoWithUploader {
  'uploaderName' : string,
  'blob' : ExternalBlob,
  'uploader' : Principal,
}
export interface PublicMemberDirectoryEntry {
  'name' : string,
  'rank' : bigint,
  'isClaimed' : boolean,
  'rating' : bigint,
  'photo' : [] | [Photo],
}
export interface RegisteredPlayer {
  'id' : Principal,
  'name' : string,
  'rating' : bigint,
  'photo' : [] | [Photo],
}
export interface SessionInput {
  'sessionType' : string,
  'date' : Time,
  'notes' : string,
}
export type Time = bigint;
export interface TournamentLeaderboardEntry {
  'gamesLost' : bigint,
  'player' : Principal,
  'rank' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'playerName' : string,
  'playerPhoto' : [] | [Photo],
  'gamesWon' : bigint,
  'points' : bigint,
}
export interface TournamentMatchScore {
  'status' : MatchStatus,
  'scoreA' : bigint,
  'scoreB' : bigint,
  'rejectionReason' : [] | [string],
  'tableNumber' : bigint,
  'playerA' : Principal,
  'playerB' : Principal,
  'timestamp' : Time,
  'roundNumber' : bigint,
}
export interface TournamentPlayerStats {
  'gamesLost' : bigint,
  'player' : Principal,
  'wins' : bigint,
  'losses' : bigint,
  'gamesWon' : bigint,
  'points' : bigint,
}
export interface TournamentRound {
  'matches' : Array<TournamentMatchScore>,
  'roundNumber' : bigint,
  'isComplete' : boolean,
}
export interface TournamentState {
  'status' : TournamentStatus,
  'registeredPlayers' : Array<RegisteredPlayer>,
  'currentRound' : bigint,
  'playerStats' : Array<TournamentPlayerStats>,
  'endTimestamp' : [] | [Time],
  'startTimestamp' : [] | [Time],
  'rounds' : Array<TournamentRound>,
}
export type TournamentStatus = { 'notStarted' : null } |
  { 'active' : null } |
  { 'completed' : null } |
  { 'announced' : null } |
  { 'paused' : null };
export interface UserProfile { 'name' : string, 'photo' : [] | [Photo] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklySession {
  'sessionType' : string,
  'date' : Time,
  'notes' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPhotoToBanner' : ActorMethod<[string], undefined>,
  'addPlayerToTournament' : ActorMethod<[Principal], undefined>,
  'announceTournament' : ActorMethod<[], undefined>,
  'appointScoreAuthAdmin' : ActorMethod<[Principal], undefined>,
  'approveMatch' : ActorMethod<[Time], undefined>,
  'approveTournamentMatch' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimMemberAccount' : ActorMethod<[string], undefined>,
  'createMemberWithClaimCode' : ActorMethod<[string, [] | [Photo]], string>,
  'createSession' : ActorMethod<[SessionInput], undefined>,
  'deleteBannerPhoto' : ActorMethod<[string], undefined>,
  'deleteMember' : ActorMethod<[Principal], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'deleteSession' : ActorMethod<[Time], undefined>,
  'endTournament' : ActorMethod<[], undefined>,
  'getAllBannerPhotoKeys' : ActorMethod<[], Array<string>>,
  'getApprovedMatches' : ActorMethod<[], Array<MatchScore>>,
  'getBannerPhotoCount' : ActorMethod<[], bigint>,
  'getBannerPhotos' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryLeaderboards' : ActorMethod<[], Array<CategoryLeaderboard>>,
  'getLeaderboard' : ActorMethod<[], Array<MemberProfileWithRank>>,
  'getMemberDirectory' : ActorMethod<[], Array<PublicMemberDirectoryEntry>>,
  'getMemberProfile' : ActorMethod<[Principal], [] | [MemberProfile]>,
  'getPendingMatches' : ActorMethod<[], Array<MatchScore>>,
  'getPhoto' : ActorMethod<[string], [] | [PhotoWithUploader]>,
  'getPhotos' : ActorMethod<[], Array<[string, PhotoWithUploader]>>,
  'getPlayerMatchHistory' : ActorMethod<[Principal], Array<MatchScore>>,
  'getRegisteredPlayerDetails' : ActorMethod<[], Array<RegisteredPlayer>>,
  'getSchedule' : ActorMethod<[], Array<WeeklySession>>,
  'getScoreAuthAdmins' : ActorMethod<[], Array<Principal>>,
  'getTournamentLeaderboard' : ActorMethod<
    [],
    Array<TournamentLeaderboardEntry>
  >,
  'getTournamentState' : ActorMethod<[], TournamentState>,
  'getUnclaimedMembers' : ActorMethod<[], Array<[string, OneTimeClaimMember]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importMemberData' : ActorMethod<
    [Array<[Principal, MemberProfile]>],
    undefined
  >,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isScoreAuthAdmin' : ActorMethod<[Principal], boolean>,
  'isTournamentActive' : ActorMethod<[], boolean>,
  'pauseTournament' : ActorMethod<[], undefined>,
  'registerForTournament' : ActorMethod<[], undefined>,
  'rejectMatch' : ActorMethod<[Time, [] | [string]], undefined>,
  'rejectTournamentMatch' : ActorMethod<
    [bigint, bigint, [] | [string]],
    undefined
  >,
  'removePhotoFromBanner' : ActorMethod<[string], undefined>,
  'removePlayerFromTournament' : ActorMethod<[Principal], undefined>,
  'removeScoreAuthAdmin' : ActorMethod<[Principal], undefined>,
  'reorderBannerPhotos' : ActorMethod<[Array<string>], undefined>,
  'resetTournament' : ActorMethod<[], undefined>,
  'restoreDataFromLegacy' : ActorMethod<
    [Array<[string, BannerPhoto]>, Array<string>],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTournament' : ActorMethod<[], undefined>,
  'submitMatchScore' : ActorMethod<[Principal, bigint, bigint], undefined>,
  'submitMatchScoreWithPlayers' : ActorMethod<
    [Principal, Principal, bigint, bigint],
    undefined
  >,
  'submitTournamentMatchScore' : ActorMethod<
    [Principal, bigint, bigint, bigint, bigint],
    undefined
  >,
  'submitTournamentMatchScoreWithPlayers' : ActorMethod<
    [Principal, Principal, bigint, bigint, bigint, bigint],
    undefined
  >,
  'unregisterFromTournament' : ActorMethod<[], undefined>,
  'updateMemberPhoto' : ActorMethod<[Photo], undefined>,
  'updateSession' : ActorMethod<[Time, SessionInput], undefined>,
  'uploadBannerPhoto' : ActorMethod<[string, string], undefined>,
  'uploadPhoto' : ActorMethod<[string, ExternalBlob, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];