/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Photo = IDL.Vec(IDL.Nat8);
export const SessionInput = IDL.Record({
  'sessionType' : IDL.Text,
  'date' : Time,
  'notes' : IDL.Text,
});
export const MatchStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const MatchScore = IDL.Record({
  'status' : MatchStatus,
  'scoreA' : IDL.Nat,
  'scoreB' : IDL.Nat,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'kFactor' : IDL.Nat,
  'ratingChangeA' : IDL.Int,
  'ratingChangeB' : IDL.Int,
  'playerA' : IDL.Principal,
  'playerB' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'photo' : IDL.Opt(Photo),
});
export const EloRating = IDL.Nat;
export const MemberProfileWithRank = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'rating' : EloRating,
  'photo' : IDL.Opt(Photo),
  'matchHistory' : IDL.Vec(MatchScore),
});
export const CategoryLeaderboard = IDL.Record({
  'categoryName' : IDL.Text,
  'players' : IDL.Vec(MemberProfileWithRank),
});
export const PublicMemberDirectoryEntry = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Nat,
  'isClaimed' : IDL.Bool,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(Photo),
});
export const MemberProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'rating' : EloRating,
  'photo' : IDL.Opt(Photo),
  'matchHistory' : IDL.Vec(MatchScore),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoWithUploader = IDL.Record({
  'uploaderName' : IDL.Text,
  'blob' : ExternalBlob,
  'uploader' : IDL.Principal,
});
export const RegisteredPlayer = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
  'photo' : IDL.Opt(Photo),
});
export const WeeklySession = IDL.Record({
  'sessionType' : IDL.Text,
  'date' : Time,
  'notes' : IDL.Text,
});
export const TournamentLeaderboardEntry = IDL.Record({
  'gamesLost' : IDL.Nat,
  'player' : IDL.Principal,
  'rank' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'playerName' : IDL.Text,
  'playerPhoto' : IDL.Opt(Photo),
  'gamesWon' : IDL.Nat,
  'points' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'announced' : IDL.Null,
  'paused' : IDL.Null,
});
export const TournamentPlayerStats = IDL.Record({
  'gamesLost' : IDL.Nat,
  'player' : IDL.Principal,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'gamesWon' : IDL.Nat,
  'points' : IDL.Nat,
});
export const TournamentMatchScore = IDL.Record({
  'status' : MatchStatus,
  'scoreA' : IDL.Nat,
  'scoreB' : IDL.Nat,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'tableNumber' : IDL.Nat,
  'playerA' : IDL.Principal,
  'playerB' : IDL.Principal,
  'timestamp' : Time,
  'roundNumber' : IDL.Nat,
});
export const TournamentRound = IDL.Record({
  'matches' : IDL.Vec(TournamentMatchScore),
  'roundNumber' : IDL.Nat,
  'isComplete' : IDL.Bool,
});
export const TournamentState = IDL.Record({
  'status' : TournamentStatus,
  'registeredPlayers' : IDL.Vec(RegisteredPlayer),
  'currentRound' : IDL.Nat,
  'playerStats' : IDL.Vec(TournamentPlayerStats),
  'endTimestamp' : IDL.Opt(Time),
  'startTimestamp' : IDL.Opt(Time),
  'rounds' : IDL.Vec(TournamentRound),
});
export const OneTimeClaimMember = IDL.Record({
  'name' : IDL.Text,
  'eloRating' : IDL.Nat,
  'createdTimestamp' : Time,
  'photo' : IDL.Opt(Photo),
});
export const BannerPhoto = IDL.Record({
  'uploaderName' : IDL.Text,
  'photoKey' : IDL.Text,
  'uploadTimestamp' : Time,
  'uploader' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPhotoToBanner' : IDL.Func([IDL.Text], [], []),
  'addPlayerToTournament' : IDL.Func([IDL.Principal], [], []),
  'announceTournament' : IDL.Func([], [], []),
  'appointScoreAuthAdmin' : IDL.Func([IDL.Principal], [], []),
  'approveMatch' : IDL.Func([Time], [], []),
  'approveTournamentMatch' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimMemberAccount' : IDL.Func([IDL.Text], [], []),
  'createMemberWithClaimCode' : IDL.Func(
      [IDL.Text, IDL.Opt(Photo)],
      [IDL.Text],
      [],
    ),
  'createSession' : IDL.Func([SessionInput], [], []),
  'deleteBannerPhoto' : IDL.Func([IDL.Text], [], []),
  'deleteMember' : IDL.Func([IDL.Principal], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'deleteSession' : IDL.Func([Time], [], []),
  'endTournament' : IDL.Func([], [], []),
  'getAllBannerPhotoKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getApprovedMatches' : IDL.Func([], [IDL.Vec(MatchScore)], ['query']),
  'getBannerPhotoCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBannerPhotos' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryLeaderboards' : IDL.Func(
      [],
      [IDL.Vec(CategoryLeaderboard)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(MemberProfileWithRank)], ['query']),
  'getMemberDirectory' : IDL.Func(
      [],
      [IDL.Vec(PublicMemberDirectoryEntry)],
      ['query'],
    ),
  'getMemberProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberProfile)],
      ['query'],
    ),
  'getPendingMatches' : IDL.Func([], [IDL.Vec(MatchScore)], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [IDL.Opt(PhotoWithUploader)], ['query']),
  'getPhotos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PhotoWithUploader))],
      ['query'],
    ),
  'getPlayerMatchHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MatchScore)],
      ['query'],
    ),
  'getRegisteredPlayerDetails' : IDL.Func(
      [],
      [IDL.Vec(RegisteredPlayer)],
      ['query'],
    ),
  'getSchedule' : IDL.Func([], [IDL.Vec(WeeklySession)], ['query']),
  'getScoreAuthAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getTournamentLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(TournamentLeaderboardEntry)],
      ['query'],
    ),
  'getTournamentState' : IDL.Func([], [TournamentState], ['query']),
  'getUnclaimedMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, OneTimeClaimMember))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importMemberData' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, MemberProfile))],
      [],
      [],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isScoreAuthAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isTournamentActive' : IDL.Func([], [IDL.Bool], ['query']),
  'pauseTournament' : IDL.Func([], [], []),
  'registerForTournament' : IDL.Func([], [], []),
  'rejectMatch' : IDL.Func([Time, IDL.Opt(IDL.Text)], [], []),
  'rejectTournamentMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'removePhotoFromBanner' : IDL.Func([IDL.Text], [], []),
  'removePlayerFromTournament' : IDL.Func([IDL.Principal], [], []),
  'removeScoreAuthAdmin' : IDL.Func([IDL.Principal], [], []),
  'reorderBannerPhotos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'resetTournament' : IDL.Func([], [], []),
  'restoreDataFromLegacy' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, BannerPhoto)), IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTournament' : IDL.Func([], [], []),
  'submitMatchScore' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat], [], []),
  'submitMatchScoreWithPlayers' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'submitTournamentMatchScore' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'submitTournamentMatchScoreWithPlayers' : IDL.Func(
      [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'unregisterFromTournament' : IDL.Func([], [], []),
  'updateMemberPhoto' : IDL.Func([Photo], [], []),
  'updateSession' : IDL.Func([Time, SessionInput], [], []),
  'uploadBannerPhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadPhoto' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Photo = IDL.Vec(IDL.Nat8);
  const SessionInput = IDL.Record({
    'sessionType' : IDL.Text,
    'date' : Time,
    'notes' : IDL.Text,
  });
  const MatchStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const MatchScore = IDL.Record({
    'status' : MatchStatus,
    'scoreA' : IDL.Nat,
    'scoreB' : IDL.Nat,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'kFactor' : IDL.Nat,
    'ratingChangeA' : IDL.Int,
    'ratingChangeB' : IDL.Int,
    'playerA' : IDL.Principal,
    'playerB' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'photo' : IDL.Opt(Photo),
  });
  const EloRating = IDL.Nat;
  const MemberProfileWithRank = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'rating' : EloRating,
    'photo' : IDL.Opt(Photo),
    'matchHistory' : IDL.Vec(MatchScore),
  });
  const CategoryLeaderboard = IDL.Record({
    'categoryName' : IDL.Text,
    'players' : IDL.Vec(MemberProfileWithRank),
  });
  const PublicMemberDirectoryEntry = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Nat,
    'isClaimed' : IDL.Bool,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(Photo),
  });
  const MemberProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'rating' : EloRating,
    'photo' : IDL.Opt(Photo),
    'matchHistory' : IDL.Vec(MatchScore),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoWithUploader = IDL.Record({
    'uploaderName' : IDL.Text,
    'blob' : ExternalBlob,
    'uploader' : IDL.Principal,
  });
  const RegisteredPlayer = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
    'photo' : IDL.Opt(Photo),
  });
  const WeeklySession = IDL.Record({
    'sessionType' : IDL.Text,
    'date' : Time,
    'notes' : IDL.Text,
  });
  const TournamentLeaderboardEntry = IDL.Record({
    'gamesLost' : IDL.Nat,
    'player' : IDL.Principal,
    'rank' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'playerName' : IDL.Text,
    'playerPhoto' : IDL.Opt(Photo),
    'gamesWon' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'announced' : IDL.Null,
    'paused' : IDL.Null,
  });
  const TournamentPlayerStats = IDL.Record({
    'gamesLost' : IDL.Nat,
    'player' : IDL.Principal,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'gamesWon' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const TournamentMatchScore = IDL.Record({
    'status' : MatchStatus,
    'scoreA' : IDL.Nat,
    'scoreB' : IDL.Nat,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'tableNumber' : IDL.Nat,
    'playerA' : IDL.Principal,
    'playerB' : IDL.Principal,
    'timestamp' : Time,
    'roundNumber' : IDL.Nat,
  });
  const TournamentRound = IDL.Record({
    'matches' : IDL.Vec(TournamentMatchScore),
    'roundNumber' : IDL.Nat,
    'isComplete' : IDL.Bool,
  });
  const TournamentState = IDL.Record({
    'status' : TournamentStatus,
    'registeredPlayers' : IDL.Vec(RegisteredPlayer),
    'currentRound' : IDL.Nat,
    'playerStats' : IDL.Vec(TournamentPlayerStats),
    'endTimestamp' : IDL.Opt(Time),
    'startTimestamp' : IDL.Opt(Time),
    'rounds' : IDL.Vec(TournamentRound),
  });
  const OneTimeClaimMember = IDL.Record({
    'name' : IDL.Text,
    'eloRating' : IDL.Nat,
    'createdTimestamp' : Time,
    'photo' : IDL.Opt(Photo),
  });
  const BannerPhoto = IDL.Record({
    'uploaderName' : IDL.Text,
    'photoKey' : IDL.Text,
    'uploadTimestamp' : Time,
    'uploader' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPhotoToBanner' : IDL.Func([IDL.Text], [], []),
    'addPlayerToTournament' : IDL.Func([IDL.Principal], [], []),
    'announceTournament' : IDL.Func([], [], []),
    'appointScoreAuthAdmin' : IDL.Func([IDL.Principal], [], []),
    'approveMatch' : IDL.Func([Time], [], []),
    'approveTournamentMatch' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimMemberAccount' : IDL.Func([IDL.Text], [], []),
    'createMemberWithClaimCode' : IDL.Func(
        [IDL.Text, IDL.Opt(Photo)],
        [IDL.Text],
        [],
      ),
    'createSession' : IDL.Func([SessionInput], [], []),
    'deleteBannerPhoto' : IDL.Func([IDL.Text], [], []),
    'deleteMember' : IDL.Func([IDL.Principal], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'deleteSession' : IDL.Func([Time], [], []),
    'endTournament' : IDL.Func([], [], []),
    'getAllBannerPhotoKeys' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getApprovedMatches' : IDL.Func([], [IDL.Vec(MatchScore)], ['query']),
    'getBannerPhotoCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBannerPhotos' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryLeaderboards' : IDL.Func(
        [],
        [IDL.Vec(CategoryLeaderboard)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(MemberProfileWithRank)],
        ['query'],
      ),
    'getMemberDirectory' : IDL.Func(
        [],
        [IDL.Vec(PublicMemberDirectoryEntry)],
        ['query'],
      ),
    'getMemberProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberProfile)],
        ['query'],
      ),
    'getPendingMatches' : IDL.Func([], [IDL.Vec(MatchScore)], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [IDL.Opt(PhotoWithUploader)], ['query']),
    'getPhotos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PhotoWithUploader))],
        ['query'],
      ),
    'getPlayerMatchHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MatchScore)],
        ['query'],
      ),
    'getRegisteredPlayerDetails' : IDL.Func(
        [],
        [IDL.Vec(RegisteredPlayer)],
        ['query'],
      ),
    'getSchedule' : IDL.Func([], [IDL.Vec(WeeklySession)], ['query']),
    'getScoreAuthAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getTournamentLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(TournamentLeaderboardEntry)],
        ['query'],
      ),
    'getTournamentState' : IDL.Func([], [TournamentState], ['query']),
    'getUnclaimedMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, OneTimeClaimMember))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importMemberData' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, MemberProfile))],
        [],
        [],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isScoreAuthAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isTournamentActive' : IDL.Func([], [IDL.Bool], ['query']),
    'pauseTournament' : IDL.Func([], [], []),
    'registerForTournament' : IDL.Func([], [], []),
    'rejectMatch' : IDL.Func([Time, IDL.Opt(IDL.Text)], [], []),
    'rejectTournamentMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'removePhotoFromBanner' : IDL.Func([IDL.Text], [], []),
    'removePlayerFromTournament' : IDL.Func([IDL.Principal], [], []),
    'removeScoreAuthAdmin' : IDL.Func([IDL.Principal], [], []),
    'reorderBannerPhotos' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'resetTournament' : IDL.Func([], [], []),
    'restoreDataFromLegacy' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, BannerPhoto)), IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTournament' : IDL.Func([], [], []),
    'submitMatchScore' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat], [], []),
    'submitMatchScoreWithPlayers' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'submitTournamentMatchScore' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'submitTournamentMatchScoreWithPlayers' : IDL.Func(
        [IDL.Principal, IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'unregisterFromTournament' : IDL.Func([], [], []),
    'updateMemberPhoto' : IDL.Func([Photo], [], []),
    'updateSession' : IDL.Func([Time, SessionInput], [], []),
    'uploadBannerPhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadPhoto' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };