/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PhotoWithUploader {
    uploaderName: string;
    blob: ExternalBlob;
    uploader: Principal;
}
export interface SessionInput {
    sessionType: string;
    date: Time;
    notes: string;
}
export type Photo = Uint8Array;
export type Time = bigint;
export interface RegisteredPlayer {
    id: Principal;
    name: string;
    rating: bigint;
    photo?: Photo;
}
export interface BannerPhoto {
    uploaderName: string;
    photoKey: string;
    uploadTimestamp: Time;
    uploader: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TournamentMatchScore {
    status: MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason?: string;
    tableNumber: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: Time;
    roundNumber: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TournamentRound {
    matches: Array<TournamentMatchScore>;
    roundNumber: bigint;
    isComplete: boolean;
}
export interface MemberProfile {
    id: Principal;
    name: string;
    rating: EloRating;
    photo?: Photo;
    matchHistory: Array<MatchScore>;
}
export interface TournamentState {
    status: TournamentStatus;
    registeredPlayers: Array<RegisteredPlayer>;
    currentRound: bigint;
    playerStats: Array<TournamentPlayerStats>;
    endTimestamp?: Time;
    startTimestamp?: Time;
    rounds: Array<TournamentRound>;
}
export interface PublicMemberDirectoryEntry {
    name: string;
    rank: bigint;
    isClaimed: boolean;
    rating: bigint;
    photo?: Photo;
}
export interface TournamentLeaderboardEntry {
    gamesLost: bigint;
    player: Principal;
    rank: bigint;
    wins: bigint;
    losses: bigint;
    playerName: string;
    playerPhoto?: Photo;
    gamesWon: bigint;
    points: bigint;
}
export interface WeeklySession {
    sessionType: string;
    date: Time;
    notes: string;
}
export interface MatchScore {
    status: MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason?: string;
    kFactor: bigint;
    ratingChangeA: bigint;
    ratingChangeB: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: Time;
}
export interface TournamentPlayerStats {
    gamesLost: bigint;
    player: Principal;
    wins: bigint;
    losses: bigint;
    gamesWon: bigint;
    points: bigint;
}
export interface OneTimeClaimMember {
    name: string;
    eloRating: bigint;
    createdTimestamp: Time;
    photo?: Photo;
}
export interface MemberProfileWithRank {
    id: Principal;
    name: string;
    rank: bigint;
    rating: EloRating;
    photo?: Photo;
    matchHistory: Array<MatchScore>;
}
export type EloRating = bigint;
export interface CategoryLeaderboard {
    categoryName: string;
    players: Array<MemberProfileWithRank>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    photo?: Photo;
}
export enum MatchStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum TournamentStatus {
    notStarted = "notStarted",
    active = "active",
    completed = "completed",
    announced = "announced",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addPhotoToBanner(photoKey: string): Promise<void>;
    addPlayerToTournament(player: Principal): Promise<void>;
    announceTournament(): Promise<void>;
    appointScoreAuthAdmin(user: Principal): Promise<void>;
    approveMatch(matchTimestamp: Time): Promise<void>;
    approveTournamentMatch(roundNumber: bigint, matchIndex: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimMemberAccount(claimCode: string): Promise<void>;
    createMemberWithClaimCode(name: string, photo: Photo | null): Promise<string>;
    createSession(input: SessionInput): Promise<void>;
    deleteBannerPhoto(photoKey: string): Promise<void>;
    deleteMember(memberPrincipal: Principal): Promise<void>;
    deletePhoto(photoKey: string): Promise<void>;
    deleteSession(date: Time): Promise<void>;
    endTournament(): Promise<void>;
    getAllBannerPhotoKeys(): Promise<Array<string>>;
    getApprovedMatches(): Promise<Array<MatchScore>>;
    getBannerPhotoCount(): Promise<bigint>;
    getBannerPhotos(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryLeaderboards(): Promise<Array<CategoryLeaderboard>>;
    getLeaderboard(): Promise<Array<MemberProfileWithRank>>;
    getMemberDirectory(): Promise<Array<PublicMemberDirectoryEntry>>;
    getMemberProfile(user: Principal): Promise<MemberProfile | null>;
    getPendingMatches(): Promise<Array<MatchScore>>;
    getPhoto(photoKey: string): Promise<PhotoWithUploader | null>;
    getPhotos(): Promise<Array<[string, PhotoWithUploader]>>;
    getPlayerMatchHistory(player: Principal): Promise<Array<MatchScore>>;
    getRegisteredPlayerDetails(): Promise<Array<RegisteredPlayer>>;
    getSchedule(): Promise<Array<WeeklySession>>;
    getScoreAuthAdmins(): Promise<Array<Principal>>;
    getTournamentLeaderboard(): Promise<Array<TournamentLeaderboardEntry>>;
    getTournamentState(): Promise<TournamentState>;
    getUnclaimedMembers(): Promise<Array<[string, OneTimeClaimMember]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importMemberData(memberData: Array<[Principal, MemberProfile]>): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isScoreAuthAdmin(user: Principal): Promise<boolean>;
    isTournamentActive(): Promise<boolean>;
    pauseTournament(): Promise<void>;
    registerForTournament(): Promise<void>;
    rejectMatch(matchTimestamp: Time, reason: string | null): Promise<void>;
    rejectTournamentMatch(roundNumber: bigint, matchIndex: bigint, reason: string | null): Promise<void>;
    removePhotoFromBanner(photoKey: string): Promise<void>;
    removePlayerFromTournament(player: Principal): Promise<void>;
    removeScoreAuthAdmin(user: Principal): Promise<void>;
    reorderBannerPhotos(newOrder: Array<string>): Promise<void>;
    resetTournament(): Promise<void>;
    restoreDataFromLegacy(legacyData: Array<[string, BannerPhoto]>, legacyBannerList: Array<string>): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startTournament(): Promise<void>;
    submitMatchScore(opponent: Principal, scoreA: bigint, scoreB: bigint): Promise<void>;
    submitMatchScoreWithPlayers(player1: Principal, player2: Principal, scoreA: bigint, scoreB: bigint): Promise<void>;
    submitTournamentMatchScore(opponent: Principal, scoreA: bigint, scoreB: bigint, roundNumber: bigint, tableNumber: bigint): Promise<void>;
    submitTournamentMatchScoreWithPlayers(player1: Principal, player2: Principal, scoreA: bigint, scoreB: bigint, roundNumber: bigint, tableNumber: bigint): Promise<void>;
    unregisterFromTournament(): Promise<void>;
    updateMemberPhoto(photo: Photo): Promise<void>;
    updateSession(date: Time, input: SessionInput): Promise<void>;
    uploadBannerPhoto(photoKey: string, uploaderName: string): Promise<void>;
    uploadPhoto(photoKey: string, photoBlob: ExternalBlob, uploaderName: string): Promise<void>;
}
import type { CategoryLeaderboard as _CategoryLeaderboard, EloRating as _EloRating, ExternalBlob as _ExternalBlob, MatchScore as _MatchScore, MatchStatus as _MatchStatus, MemberProfile as _MemberProfile, MemberProfileWithRank as _MemberProfileWithRank, OneTimeClaimMember as _OneTimeClaimMember, Photo as _Photo, PhotoWithUploader as _PhotoWithUploader, PublicMemberDirectoryEntry as _PublicMemberDirectoryEntry, RegisteredPlayer as _RegisteredPlayer, Time as _Time, TournamentLeaderboardEntry as _TournamentLeaderboardEntry, TournamentMatchScore as _TournamentMatchScore, TournamentPlayerStats as _TournamentPlayerStats, TournamentRound as _TournamentRound, TournamentState as _TournamentState, TournamentStatus as _TournamentStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addPhotoToBanner(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhotoToBanner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhotoToBanner(arg0);
            return result;
        }
    }
    async addPlayerToTournament(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayerToTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayerToTournament(arg0);
            return result;
        }
    }
    async announceTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.announceTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.announceTournament();
            return result;
        }
    }
    async appointScoreAuthAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.appointScoreAuthAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.appointScoreAuthAdmin(arg0);
            return result;
        }
    }
    async approveMatch(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMatch(arg0);
            return result;
        }
    }
    async approveTournamentMatch(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTournamentMatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTournamentMatch(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimMemberAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimMemberAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimMemberAccount(arg0);
            return result;
        }
    }
    async createMemberWithClaimCode(arg0: string, arg1: Photo | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMemberWithClaimCode(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMemberWithClaimCode(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSession(arg0: SessionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async deleteBannerPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBannerPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBannerPhoto(arg0);
            return result;
        }
    }
    async deleteMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMember(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deleteSession(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSession(arg0);
            return result;
        }
    }
    async endTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endTournament();
            return result;
        }
    }
    async getAllBannerPhotoKeys(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBannerPhotoKeys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBannerPhotoKeys();
            return result;
        }
    }
    async getApprovedMatches(): Promise<Array<MatchScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedMatches();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedMatches();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBannerPhotoCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannerPhotoCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannerPhotoCount();
            return result;
        }
    }
    async getBannerPhotos(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannerPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannerPhotos();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryLeaderboards(): Promise<Array<CategoryLeaderboard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryLeaderboards();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryLeaderboards();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<MemberProfileWithRank>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberDirectory(): Promise<Array<PublicMemberDirectoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberDirectory();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberDirectory();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberProfile(arg0: Principal): Promise<MemberProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingMatches(): Promise<Array<MatchScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingMatches();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingMatches();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhoto(arg0: string): Promise<PhotoWithUploader | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhoto(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhoto(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotos(): Promise<Array<[string, PhotoWithUploader]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotos();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotos();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerMatchHistory(arg0: Principal): Promise<Array<MatchScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerMatchHistory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerMatchHistory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegisteredPlayerDetails(): Promise<Array<RegisteredPlayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegisteredPlayerDetails();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegisteredPlayerDetails();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSchedule(): Promise<Array<WeeklySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchedule();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchedule();
            return result;
        }
    }
    async getScoreAuthAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreAuthAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreAuthAdmins();
            return result;
        }
    }
    async getTournamentLeaderboard(): Promise<Array<TournamentLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentLeaderboard();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentLeaderboard();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentState(): Promise<TournamentState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentState();
                return from_candid_TournamentState_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentState();
            return from_candid_TournamentState_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnclaimedMembers(): Promise<Array<[string, OneTimeClaimMember]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnclaimedMembers();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnclaimedMembers();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async importMemberData(arg0: Array<[Principal, MemberProfile]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importMemberData(to_candid_vec_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importMemberData(to_candid_vec_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isScoreAuthAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isScoreAuthAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isScoreAuthAdmin(arg0);
            return result;
        }
    }
    async isTournamentActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTournamentActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTournamentActive();
            return result;
        }
    }
    async pauseTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseTournament();
            return result;
        }
    }
    async registerForTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForTournament();
            return result;
        }
    }
    async rejectMatch(arg0: Time, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectMatch(arg0, to_candid_opt_n71(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectMatch(arg0, to_candid_opt_n71(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async rejectTournamentMatch(arg0: bigint, arg1: bigint, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTournamentMatch(arg0, arg1, to_candid_opt_n71(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTournamentMatch(arg0, arg1, to_candid_opt_n71(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async removePhotoFromBanner(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePhotoFromBanner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePhotoFromBanner(arg0);
            return result;
        }
    }
    async removePlayerFromTournament(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePlayerFromTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePlayerFromTournament(arg0);
            return result;
        }
    }
    async removeScoreAuthAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeScoreAuthAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeScoreAuthAdmin(arg0);
            return result;
        }
    }
    async reorderBannerPhotos(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderBannerPhotos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderBannerPhotos(arg0);
            return result;
        }
    }
    async resetTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTournament();
            return result;
        }
    }
    async restoreDataFromLegacy(arg0: Array<[string, BannerPhoto]>, arg1: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreDataFromLegacy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreDataFromLegacy(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n72(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTournament();
            return result;
        }
    }
    async submitMatchScore(arg0: Principal, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMatchScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMatchScore(arg0, arg1, arg2);
            return result;
        }
    }
    async submitMatchScoreWithPlayers(arg0: Principal, arg1: Principal, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMatchScoreWithPlayers(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMatchScoreWithPlayers(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitTournamentMatchScore(arg0: Principal, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTournamentMatchScore(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTournamentMatchScore(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitTournamentMatchScoreWithPlayers(arg0: Principal, arg1: Principal, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTournamentMatchScoreWithPlayers(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTournamentMatchScoreWithPlayers(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async unregisterFromTournament(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unregisterFromTournament();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unregisterFromTournament();
            return result;
        }
    }
    async updateMemberPhoto(arg0: Photo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMemberPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMemberPhoto(arg0);
            return result;
        }
    }
    async updateSession(arg0: Time, arg1: SessionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSession(arg0, arg1);
            return result;
        }
    }
    async uploadBannerPhoto(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadBannerPhoto(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadBannerPhoto(arg0, arg1);
            return result;
        }
    }
    async uploadPhoto(arg0: string, arg1: ExternalBlob, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0, await to_candid_ExternalBlob_n74(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0, await to_candid_ExternalBlob_n74(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_CategoryLeaderboard_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryLeaderboard): CategoryLeaderboard {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MatchScore_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchScore): MatchScore {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MemberProfileWithRank_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfileWithRank): MemberProfileWithRank {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MemberProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): MemberProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_OneTimeClaimMember_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OneTimeClaimMember): OneTimeClaimMember {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
async function from_candid_PhotoWithUploader_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhotoWithUploader): Promise<PhotoWithUploader> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PublicMemberDirectoryEntry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicMemberDirectoryEntry): PublicMemberDirectoryEntry {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_RegisteredPlayer_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisteredPlayer): RegisteredPlayer {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentLeaderboardEntry_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentLeaderboardEntry): TournamentLeaderboardEntry {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentMatchScore_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentMatchScore): TournamentMatchScore {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentRound_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentRound): TournamentRound {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentState_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentState): TournamentState {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Photo]): Photo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberProfile]): MemberProfile | null {
    return value.length === 0 ? null : from_candid_MemberProfile_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhotoWithUploader]): Promise<PhotoWithUploader | null> {
    return value.length === 0 ? null : await from_candid_PhotoWithUploader_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason: [] | [string];
    kFactor: bigint;
    ratingChangeA: bigint;
    ratingChangeB: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: _Time;
}): {
    status: MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason?: string;
    kFactor: bigint;
    ratingChangeA: bigint;
    ratingChangeB: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: Time;
} {
    return {
        status: from_candid_MatchStatus_n14(_uploadFile, _downloadFile, value.status),
        scoreA: value.scoreA,
        scoreB: value.scoreB,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejectionReason)),
        kFactor: value.kFactor,
        ratingChangeA: value.ratingChangeA,
        ratingChangeB: value.ratingChangeB,
        playerA: value.playerA,
        playerB: value.playerB,
        timestamp: value.timestamp
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    photo: [] | [_Photo];
}): {
    name: string;
    photo?: Photo;
} {
    return {
        name: value.name,
        photo: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryName: string;
    players: Array<_MemberProfileWithRank>;
}): {
    categoryName: string;
    players: Array<MemberProfileWithRank>;
} {
    return {
        categoryName: value.categoryName,
        players: from_candid_vec_n26(_uploadFile, _downloadFile, value.players)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    rank: bigint;
    rating: _EloRating;
    photo: [] | [_Photo];
    matchHistory: Array<_MatchScore>;
}): {
    id: Principal;
    name: string;
    rank: bigint;
    rating: EloRating;
    photo?: Photo;
    matchHistory: Array<MatchScore>;
} {
    return {
        id: value.id,
        name: value.name,
        rank: value.rank,
        rating: value.rating,
        photo: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.photo)),
        matchHistory: from_candid_vec_n11(_uploadFile, _downloadFile, value.matchHistory)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    rank: bigint;
    isClaimed: boolean;
    rating: bigint;
    photo: [] | [_Photo];
}): {
    name: string;
    rank: bigint;
    isClaimed: boolean;
    rating: bigint;
    photo?: Photo;
} {
    return {
        name: value.name,
        rank: value.rank,
        isClaimed: value.isClaimed,
        rating: value.rating,
        photo: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    rating: _EloRating;
    photo: [] | [_Photo];
    matchHistory: Array<_MatchScore>;
}): {
    id: Principal;
    name: string;
    rating: EloRating;
    photo?: Photo;
    matchHistory: Array<MatchScore>;
} {
    return {
        id: value.id,
        name: value.name,
        rating: value.rating,
        photo: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.photo)),
        matchHistory: from_candid_vec_n11(_uploadFile, _downloadFile, value.matchHistory)
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uploaderName: string;
    blob: _ExternalBlob;
    uploader: Principal;
}): Promise<{
    uploaderName: string;
    blob: ExternalBlob;
    uploader: Principal;
}> {
    return {
        uploaderName: value.uploaderName,
        blob: await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value.blob),
        uploader: value.uploader
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    rating: bigint;
    photo: [] | [_Photo];
}): {
    id: Principal;
    name: string;
    rating: bigint;
    photo?: Photo;
} {
    return {
        id: value.id,
        name: value.name,
        rating: value.rating,
        photo: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gamesLost: bigint;
    player: Principal;
    rank: bigint;
    wins: bigint;
    losses: bigint;
    playerName: string;
    playerPhoto: [] | [_Photo];
    gamesWon: bigint;
    points: bigint;
}): {
    gamesLost: bigint;
    player: Principal;
    rank: bigint;
    wins: bigint;
    losses: bigint;
    playerName: string;
    playerPhoto?: Photo;
    gamesWon: bigint;
    points: bigint;
} {
    return {
        gamesLost: value.gamesLost,
        player: value.player,
        rank: value.rank,
        wins: value.wins,
        losses: value.losses,
        playerName: value.playerName,
        playerPhoto: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.playerPhoto)),
        gamesWon: value.gamesWon,
        points: value.points
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TournamentStatus;
    registeredPlayers: Array<_RegisteredPlayer>;
    currentRound: bigint;
    playerStats: Array<_TournamentPlayerStats>;
    endTimestamp: [] | [_Time];
    startTimestamp: [] | [_Time];
    rounds: Array<_TournamentRound>;
}): {
    status: TournamentStatus;
    registeredPlayers: Array<RegisteredPlayer>;
    currentRound: bigint;
    playerStats: Array<TournamentPlayerStats>;
    endTimestamp?: Time;
    startTimestamp?: Time;
    rounds: Array<TournamentRound>;
} {
    return {
        status: from_candid_TournamentStatus_n49(_uploadFile, _downloadFile, value.status),
        registeredPlayers: from_candid_vec_n41(_uploadFile, _downloadFile, value.registeredPlayers),
        currentRound: value.currentRound,
        playerStats: value.playerStats,
        endTimestamp: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.endTimestamp)),
        startTimestamp: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.startTimestamp)),
        rounds: from_candid_vec_n52(_uploadFile, _downloadFile, value.rounds)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matches: Array<_TournamentMatchScore>;
    roundNumber: bigint;
    isComplete: boolean;
}): {
    matches: Array<TournamentMatchScore>;
    roundNumber: bigint;
    isComplete: boolean;
} {
    return {
        matches: from_candid_vec_n55(_uploadFile, _downloadFile, value.matches),
        roundNumber: value.roundNumber,
        isComplete: value.isComplete
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason: [] | [string];
    tableNumber: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: _Time;
    roundNumber: bigint;
}): {
    status: MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason?: string;
    tableNumber: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: Time;
    roundNumber: bigint;
} {
    return {
        status: from_candid_MatchStatus_n14(_uploadFile, _downloadFile, value.status),
        scoreA: value.scoreA,
        scoreB: value.scoreB,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.rejectionReason)),
        tableNumber: value.tableNumber,
        playerA: value.playerA,
        playerB: value.playerB,
        timestamp: value.timestamp,
        roundNumber: value.roundNumber
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    eloRating: bigint;
    createdTimestamp: _Time;
    photo: [] | [_Photo];
}): {
    name: string;
    eloRating: bigint;
    createdTimestamp: Time;
    photo?: Photo;
} {
    return {
        name: value.name,
        eloRating: value.eloRating,
        createdTimestamp: value.createdTimestamp,
        photo: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.photo))
    };
}
async function from_candid_tuple_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _PhotoWithUploader]): Promise<[string, PhotoWithUploader]> {
    return [
        value[0],
        await from_candid_PhotoWithUploader_n36(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _OneTimeClaimMember]): [string, OneTimeClaimMember] {
    return [
        value[0],
        from_candid_OneTimeClaimMember_n60(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): MatchStatus {
    return "pending" in value ? MatchStatus.pending : "approved" in value ? MatchStatus.approved : "rejected" in value ? MatchStatus.rejected : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    active: null;
} | {
    completed: null;
} | {
    announced: null;
} | {
    paused: null;
}): TournamentStatus {
    return "notStarted" in value ? TournamentStatus.notStarted : "active" in value ? TournamentStatus.active : "completed" in value ? TournamentStatus.completed : "announced" in value ? TournamentStatus.announced : "paused" in value ? TournamentStatus.paused : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchScore>): Array<MatchScore> {
    return value.map((x)=>from_candid_MatchScore_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryLeaderboard>): Array<CategoryLeaderboard> {
    return value.map((x)=>from_candid_CategoryLeaderboard_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MemberProfileWithRank>): Array<MemberProfileWithRank> {
    return value.map((x)=>from_candid_MemberProfileWithRank_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicMemberDirectoryEntry>): Array<PublicMemberDirectoryEntry> {
    return value.map((x)=>from_candid_PublicMemberDirectoryEntry_n30(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _PhotoWithUploader]>): Promise<Array<[string, PhotoWithUploader]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n40(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RegisteredPlayer>): Array<RegisteredPlayer> {
    return value.map((x)=>from_candid_RegisteredPlayer_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentLeaderboardEntry>): Array<TournamentLeaderboardEntry> {
    return value.map((x)=>from_candid_TournamentLeaderboardEntry_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentRound>): Array<TournamentRound> {
    return value.map((x)=>from_candid_TournamentRound_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentMatchScore>): Array<TournamentMatchScore> {
    return value.map((x)=>from_candid_TournamentMatchScore_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _OneTimeClaimMember]>): Array<[string, OneTimeClaimMember]> {
    return value.map((x)=>from_candid_tuple_n59(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MatchScore_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchScore): _MatchScore {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_MatchStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): _MatchStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_MemberProfile_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberProfile): _MemberProfile {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n73(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Photo | null): [] | [_Photo] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    rating: EloRating;
    photo?: Photo;
    matchHistory: Array<MatchScore>;
}): {
    id: Principal;
    name: string;
    rating: _EloRating;
    photo: [] | [_Photo];
    matchHistory: Array<_MatchScore>;
} {
    return {
        id: value.id,
        name: value.name,
        rating: value.rating,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        matchHistory: to_candid_vec_n66(_uploadFile, _downloadFile, value.matchHistory)
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason?: string;
    kFactor: bigint;
    ratingChangeA: bigint;
    ratingChangeB: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: Time;
}): {
    status: _MatchStatus;
    scoreA: bigint;
    scoreB: bigint;
    rejectionReason: [] | [string];
    kFactor: bigint;
    ratingChangeA: bigint;
    ratingChangeB: bigint;
    playerA: Principal;
    playerB: Principal;
    timestamp: _Time;
} {
    return {
        status: to_candid_MatchStatus_n69(_uploadFile, _downloadFile, value.status),
        scoreA: value.scoreA,
        scoreB: value.scoreB,
        rejectionReason: value.rejectionReason ? candid_some(value.rejectionReason) : candid_none(),
        kFactor: value.kFactor,
        ratingChangeA: value.ratingChangeA,
        ratingChangeB: value.ratingChangeB,
        playerA: value.playerA,
        playerB: value.playerB,
        timestamp: value.timestamp
    };
}
function to_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    photo?: Photo;
}): {
    name: string;
    photo: [] | [_Photo];
} {
    return {
        name: value.name,
        photo: value.photo ? candid_some(value.photo) : candid_none()
    };
}
function to_candid_tuple_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, MemberProfile]): [Principal, _MemberProfile] {
    return [
        value[0],
        to_candid_MemberProfile_n64(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == MatchStatus.pending ? {
        pending: null
    } : value == MatchStatus.approved ? {
        approved: null
    } : value == MatchStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, MemberProfile]>): Array<[Principal, _MemberProfile]> {
    return value.map((x)=>to_candid_tuple_n63(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MatchScore>): Array<_MatchScore> {
    return value.map((x)=>to_candid_MatchScore_n67(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
